name: test with TF

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [macos-latest]

    steps:
      - uses: "actions/checkout@v3"
      - name: Create directory
        run: |
          mkdir -p /tmp/grain
          cp -r . /tmp/grain
      - name: test with TF
        run: |
          set -xe
          export PYTHON_VERSION=${{ matrix.python-version }}
          export PYTHON_MAJOR_VERSION=$(echo $PYTHON_VERSION | cut -d. -f1)
          export PYTHON_MINOR_VERSION=$(echo $PYTHON_VERSION | cut -d. -f2)
          export PYENV_PYTHON_VERSION="3.11"
          export BAZEL_VERSION="7.1.1"
          export OUTPUT_DIR="/tmp/grain"
          export SOURCE_DIR="/tmp/grain"
          . "${SOURCE_DIR}"'/grain/oss/runner_common.sh'
          install_and_init_pyenv
          $PYTHON_BIN -m pip install tensorflow array-record
          export PYTHONVERBOSE=2
          export PYTHON_FROZEN_MODULES=off
          $PYTHON_BIN "${SOURCE_DIR}"'/grain/oss/test_with_tf.py'
